---
# tasks file for nfsserver
- name: mkdir dir for nfs
  file:
    path: /srv/nfs_share
    state: directory

- name: create upload dir
  file:
    path: /srv/nfs_share/upload
    state: directory
    owner: nobody
    group: nobody
    mode: "0777"  

- name: create test file
  shell:
    cmd: touch /srv/nfs_share/upload/file{1..4}
  become: no    

- name: template export file
  template:
    src: templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"

- name: start nfs service
  systemd:
    name: nfs-server.service
    enabled: yes
    state: started
