---
# tasks file for nfsclient

- name: create nsf folder
  file:
    path: /mnt/nfs_share
    state: directory

- name: mount remote dir
  ansible.posix.mount:
    src: 192.168.56.66:/srv/nfs_share
    path: /mnt/nfs_share
    boot: yes
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
