---
# tasks file for nfsclient

- name: create nsf folder
  file:
    path: /mnt/nfs_share
    state: directory

- name: mount remote dir
  ansible.posix.mount:
    src: 192.168.56.66:/srv/nfs_share
    path: /mnt/nfs_share
    boot: yes
    opts: rw,sync,hard
    state: mounted
    fstype: nfs

- name: test permissions upload dir
  file:
    path: /mnt/nfs_share/upload/testpermmfile
    state: touch
    mode: u=rw,g=rw,o=rw

- name: cat upload
  shell:
    cmd: ls -a /mnt/nfs_share/upload
  register: result  
