---
- name: NFS to server

  hosts: server
  become: true
  roles:
    - firewalld
    - nfsserver

- name: NFS to client
  hosts: client
  become: true
  roles:
    - firewalld
    - nfsclient
      

  post_tasks:
    - name: show upload dir
      debug:
        var: "{{item}}"
      with_items:
        - result.stdout_lines
        - showmount.stdout


   
 
  
