---
- name: NFS to server

  hosts: server
  become: true
  roles:
    - nfsserver
    - firewalld

- name: NFS to client
  hosts: client
  become: true
  roles:
    - nfsclient
    - firewalld

  post_tasks:
    - name: show upload dir
      debug:
        var: result.stdout_lines


   
 
  
