---

- name: start firewalld
  systemd:
    name: firewalld.service
    enabled: yes
    state: started

- name: add rules to firewalld
  ansible.posix.firewalld:
    #zone: public
    service: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - nfs3
    - rpc-bind
    - mountd  
